name: customer-management-system
services:
  customer-db:
    image: postgres:16
    container_name: customer-db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - customer_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=54321
      - POSTGRES_DB=customerDb
    networks:
      - common

  customer-service:
    build: ./customerService
    container_name: customer-service
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./customerService:/app
    depends_on:
      - customer-db
    networks:
      - common


volumes:
  customer_db:

networks:
  common:
    driver: bridge