version: '3.8'

services:
  customer-db:
    image: postgres:16
    container_name: customer-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 54321
      POSTGRES_DB: customerDb

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mert@mail.com
      PGADMIN_DEFAULT_PASSWORD: 54321
    ports:
      - "5080:80"
    depends_on:
      - customer-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-service
    depends_on:
      - customer-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customerDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 54321


volumes:
  customer_db:

