spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerDb
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
